version: "3"
services:
  web:
    build: ./web
    container_name: web
    ports:
      - 80:80
      - 443:443
      - 4200:4200
    volumes:
      - ./web:/app
      - /app/node_modules
    networks:
      - app-network

  api:
    build: ./api
    container_name: api
    ports:
      - 5000:5000
    volumes:
      - ./api/:/app
    networks:
      - app-network

  db:
    image: postgres:13.0
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: jedi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
